### ISSUE TITLE
Error code DPE01 An error occured while publishing your draft

### ISSUE THREAD

**Issue by starrychloe** [AkashaProject/Community#186]
#### System information

AKASHA version: ` 0.6.2`

Operating System: ` Windows 8.1`

#### Expected behaviour
Expected to post.

#### Actual behaviour
Did not post.

#### Steps to reproduce the problem
Create post. Click publish. (One time, with only 10 manna, it kept saying to mannafy, even though I already had manna. It was very confusing. I finally did 100 manna and it tried to post, but failed here.)

**Comment by RMBLRX** [comment]
I'm having the same issue with 1003 mana.  I haven't been able to post today.  I had it first with [a post containing 7 new tags](https://rinkeby.etherscan.io/tx/0x75a46de0f94fd2de726470369956e170c63452ab3703a486410e83a12c96df27) and then again on [one with 4 new tags](https://rinkeby.etherscan.io/tx/0x2755e1e601732de7ffbb7b909b5116f0fd9d33d2c5b4e3830d77ea6a781d4e0d).  Both are links.

I'm not sure of all the associated mana costs, but I've posted plenty of new tags on links in the past without issue.

**Comment by RMBLRX** [comment]
Getting this again: https://rinkeby.etherscan.io/tx/0x291de24f0448e66451a7717e65c428db1cf46c8b19a1e666913420f188238cf4

Not sure what causes it.  The last time it was happening, I think that the only reason it stopped was because I upgraded to 0.7.1.  Now after a while of using 0.7.2, it's cropped up again.  I see no error in the Rinkeby or IPFS logs.  The tags I'm trying to post with include _1994_, _hideo-kojima_, _game_, _gaming_, _classic-gaming_, _sega-saturn_, _pc-98_, _policenauts_ _hidden-gem_, and _psx_.

**Comment by RMBLRX** [comment]
Well it looks like we can't have numbers in the tags, because after I removed _1994_ and _pc-98_, I was able to post.

**Comment by SeverS** [comment]
Should be ok now. closing.

Thanks for feedback!
