### ISSUE TITLE
Latest entry not shown in latest entries

### ISSUE THREAD

**Issue by onbjerg** [AkashaProject/Community#69]
Given these two columns:

![Imgur](https://i.imgur.com/tdpafCi.jpg)

Shouldn't Peter's post be in the latest entries, since it's newer than the National Geographic one?

**Comment by bogdanbrezuica** [comment]
Hey Oliver, nice to see you playing with Akasha :) Yes, that entry should be displayed in the Latest entries column. Unfortunately, this looks a lot like an old geth issue that we ran into some time ago. That issue was fixed and we couldn't reproduce it anymore (until now...). So I will leave this issue open and hopefully we will have more info the next time we find it.
